const MAX_RECENT_ITEMS = 5;
const MAX_POST_LENGTH = 2;
const PAGE_WINDOW_LENGTH = 3;
const MAX_TRENDING_POSTS = 5;

module.exports = {
    MAX_RECENT_ITEMS: MAX_RECENT_ITEMS,
    MAX_POST_LENGTH: MAX_POST_LENGTH,
    PAGE_WINDOW_LENGTH: PAGE_WINDOW_LENGTH,
    MAX_TRENDING_POSTS: MAX_TRENDING_POSTS,
}